name: buddiesgram
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  firebase_core: ^0.5.0+1
  curved_navigation_bar:
  cloud_firestore: ^0.14.0
  flutter:
    sdk: flutter
  image: ^2.0.7
  animator: ^0.1.4
  image_picker: ^0.6.0+2
  google_sign_in: ^4.0.1+1
  timeago: ^2.0.17
  cached_network_image: ^2.0.0
  firebase_auth: ^0.18.0
  geolocator: ^5.0.1
  uuid: ^2.0.0
  cupertino_icons: ^1.0.2
  path_provider: ^1.6.27
  firebase_messaging: ^7.0.3
  firebase_storage: ^5.2.0
  flutter_svg:
  image_editor_pro: ^1.0.9

  image_cropper: ^1.4.0
  google_mobile_ads: ^0.12.0
  provider: ^4.3.2+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2
  firexcode:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
